baseURL = "/"
languageCode = "en-us"
author = "Hugh Paterson III and Eugene Neighbors"
title = "Hugh Paterson III for Eugene City Council"
theme = "kube"
description = "Hugh Paterson III is passionate about a better Eugene for today and tomorrow. We want to see a more supportive Eugene City Government. Hugh Paterson III is our choice."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Eugene Neighbors" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "vote4hugh@gmail.com"

  [Params.seo.webmaster_verifications]
    google = "UA-25742240-2" # Optional, Google verification code
    

[[menu.main]]
    name = "Events"
    weight = -100
    url = "/blog/"

[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"

[[menu.main]]
        name = "Positions"
        weight = -100
        url = "/docs/"

[[menu.main]]
    name = "About Hugh"
    weight = -100
    url = "/about/"
